# Generated by Django 2.2.12 on 2020-06-28 08:27

import app.ticket.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('ticket_uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('sole_uuid', models.CharField(blank=True, help_text='唯一id，一般由前端传入', max_length=100, null=True)),
                ('about_users', models.CharField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(help_text='当前状态', max_length=100)),
                ('ticket_type', models.CharField(help_text='工单类型', max_length=100)),
                ('request_id', models.CharField(default=app.ticket.models.setRequestID, max_length=100)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_create_user', to=settings.AUTH_USER_MODEL)),
                ('last_reviser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_last_reviser', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, help_text='发起人：工单的发起人', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket.Ticket')),
                ('open_time', models.DateTimeField()),
                ('solution', models.TextField(blank=True, help_text='解决方案', null=True)),
            ],
            bases=('ticket.ticket',),
        ),
    ]
