# Generated by Django 2.2.12 on 2020-06-28 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('workflow', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='WorkflowAboutPeople',
            field=models.ForeignKey(blank=True, help_text='相关人', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_Workflow_about_people', to='workflow.WorkflowAboutPeople'),
        ),
        migrations.AddField(
            model_name='event',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='审批人', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='even_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='approver_group',
            field=models.ForeignKey(blank=True, help_text='审批组', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_approver_group', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='assigner',
            field=models.ForeignKey(blank=True, help_text='受理人', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_assigner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='assigner_group',
            field=models.ForeignKey(help_text='受理组', on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_assigner_group', to='auth.Group'),
        ),
    ]
